django_htmx_modal_form/urls.py
from django.urls import path
from movie_collection import views
from django.contrib import admin


urlpatterns = [
    # path('admin/',admin.site.urls),
    path('', views.index),
    path('movies', views.movie_list, name='movie_list'),
    path('movies/add', views.add_movie, name='add_movie'),
    path('movies/<int:pk>/remove', views.remove_movie, name='remove_movie'),
    path('movies/<int:pk>/edit', views.edit_movie, name='edit_movie'),
]

movie_collection/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Movie(models.Model):

    title = models.CharField(max_length=40, unique=True)

    year = models.PositiveSmallIntegerField(
        validators=[
            MinValueValidator(1895),
            MaxValueValidator(2050),
        ]
    )

    rating = models.PositiveSmallIntegerField(choices=(
        (1, "★☆☆☆☆"),
        (2, "★★☆☆☆"),
        (3, "★★★☆☆"),
        (4, "★★★★☆"),
        (5, "★★★★★"),
    ))

movie_collection/forms.py
from django import forms

from .models import Movie


class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = ['title', 'year', 'rating']

movie_collection/views.py
import json

from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404

from .models import Movie
from .forms import MovieForm


def index(request):
    return render(request, 'index.html')


def movie_list(request):
    return render(request, 'movie_list.html', {
        'movies': Movie.objects.all(),
    })


def add_movie(request):
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "movieListChanged": None,
                        "showMessage": f"{movie.title} added."
                    })
                })
    else:
        form = MovieForm()
    return render(request, 'movie_form.html', {
        'form': form,
    })


def edit_movie(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.method == "POST":
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "movieListChanged": None,
                        "showMessage": f"{movie.title} updated."
                    })
                }
            )
    else:
        form = MovieForm(instance=movie)
    return render(request, 'movie_form.html', {
        'form': form,
        'movie': movie,
    })


@ require_POST
def remove_movie(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    movie.delete()
    return HttpResponse(
        status=204,
        headers={
            'HX-Trigger': json.dumps({
                "movieListChanged": None,
                "showMessage": f"{movie.title} deleted."
            })
        })

movie_collection/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />

    <title>My Movie Collection</title>
  </head>
  <body>
    <div class="container">
      <div class="px-5 my-5 text-center">
        <h1>My Movie Collection</h1>
        <p>A sample project that shows how to support modal forms with Django+HTMX with minimal JavaScript code.</p>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Year</th>
            <th>Rating</th>
            <th></th>
          </tr>
        </thead>
        <tbody hx-trigger="load, movieListChanged from:body" hx-get="{% url 'movie_list' %}" hx-target="this">
          <tr>
            <td class="spinner-border" role="status">
              <span class="visually-hidden">Loading...</span>
            </td>
          </tr>
        </tbody>
      </table>
      <button hx-get="{% url 'add_movie' %}" hx-target="#dialog" class="btn btn-primary">
        Add a movie
      </button>
    </div>

    <!-- Placeholder for the modal -->
    <div id="modal" class="modal fade">
      <div id="dialog" class="modal-dialog" hx-target="this"></div>
    </div>

    <!-- Empty toast to show the message -->
    <div class="toast-container position-fixed top-0 end-0 p-3">
      <div id="toast" class="toast align-items-center text-white bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
          <div id="toast-body" class="toast-body"></div>
          <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
      </div>
    </div>


    <!-- Scripts: Bootstraps, HTMX, and custom JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/htmx.org@1.6.1/dist/htmx.min.js"></script>
    <script src="{% static "dialog.js" %}"></script>
    <script src="{% static "toast.js" %}"></script>
  </body>
</html>

movie_collection/templates/movie_form.html
{% load widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
<form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title">Edit Movie</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div class="mb-3">
      <label for="{{ form.title.id_for_label }}" class="form-label">Title</label>
      {% render_field form.title class="form-control" placeholder="Back to the Future II" %}
      <div class="invalid-feedback">{{ form.title.errors|first }}</div>
    </div>
    <div class="mb-3">
      <label for="{{ form.year.id_for_label }}" class="form-label">Year</label>
      {% render_field form.year class="form-control" placeholder="1980" %}
      <div class="invalid-feedback">{{ form.year.errors|first }}</div>
    </div>
    <div class="mb-3">
      <label for="{{ form.rating.id_for_label }}" class="form-label">Rating</label >
      {% render_field form.rating class="form-control" %}
      <div class="invalid-feedback">{{ form.rating.errors|first }}</div>
    </div>
  </div>
  <div class="modal-footer">
    {% if movie %}
    <button type="button" class="btn btn-danger" hx-post="{% url 'remove_movie' pk=movie.pk %}">Remove</button>
    <span class="flex-grow-1"></span>
    {% endif %}
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
      Cancel
    </button>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>
{% endwith %}

movie_collection/templates/movie_list.html
{% for movie in movies %}
<tr id="movie-{{ movie.pk }}" class="movie-row">
  <td>{{ movie.title }}</td>
  <td>{{ movie.year }}</td>
  <td>{{ movie.get_rating_display }}</td>
  <td>
    <button class="btn btn-primary btn-sm" hx-get="{% url 'edit_movie' pk=movie.pk %}" hx-target="#dialog">Edit</button>
  </td>
</tr>
{% endfor %}